---
- name: Install apache on web servers
  tags: apache
  ansible.builtin.package:
    name:
      - "{{ apache_package }}"

- name: Ensure apache is running (ubuntu)
  tags: apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: started

- name: change email address for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: "ServerAdmin"
    line: ServerAdmin tron@somewhere.net
  when: ansible_distribution == "Fedora"
  notify: restart_apache

- name: copy html file for site
  tags: apache
  ansible.builtin.copy:
    src: defaults_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0664
...
