---
- name: Install apache on web servers (ubuntu)
  tags: apache,ubuntu
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
  when: ansible_distribution == "Ubuntu"

- name: Install apache on web servers (fedora)
  tags: apache,fedora
  ansible.builtin.dnf:
    name:
      - httpd
  when: ansible_distribution == "Fedora"

- name: Ensure apache is running (ubuntu)
  tags: apache,ubunut
  ansible.builtin.service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubunutu"

- name: Ensure apache is running (fedora)
  tags: apache,fedora
  ansible.builtin.service:
    name: httpd
    state: started
  when: ansible_distribution == "Fedora"

- name: change email address for admin
  tags: apache,fedora
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regex: "ServerAdmin"
    line: ServerAdmin somebody@somewhere.net
  when: ansible_distribution == "Fedora"
  register: httpd

- name: Restart apache (fedora)
  tags: apache,fedora
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: copy html file for site
  tags: apache,ubuntu
  ansible.builtin.copy:
    src: defaults_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0664
...
